---
####################################################################
# Config file for Chlamydomonas reinhardtii RNAseq data processing #
# Author : Domitille Jarrige                                       #
# Date   : 2021-06-12                                              #
####################################################################

parameters:
    threads: 8
    memory: 4
data_directory:
    data/
quality_control_directory:
    results/QC/
results_directory:
    results/mapping/
rhythm_directory:
    results/rhythmic_analysis/
genome_directory:
    data/genome/
nuclear_genome:
    data/genome/assembly/your_nuclear_genome.fa
organelles_genome:
    data/genome/assembly/your_organelle_genomes.fa
annotation:
    data/genome/annotation/your_annotation_all_genomes.gff3
sample_ref:
    data/sample_metadata.tsv

...